package cjx.com.diary.mode.diary;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cjx.com.diary.mode.diary.Diary;
import cjx.com.diary.mode.user.UserBean;
import cjx.com.diary.mode.weight.BodyWeightBean;

import cjx.com.diary.mode.diary.DiaryDao;
import cjx.com.diary.mode.user.UserBeanDao;
import cjx.com.diary.mode.weight.BodyWeightBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig bodyWeightBeanDaoConfig;

    private final DiaryDao diaryDao;
    private final UserBeanDao userBeanDao;
    private final BodyWeightBeanDao bodyWeightBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        bodyWeightBeanDaoConfig = daoConfigMap.get(BodyWeightBeanDao.class).clone();
        bodyWeightBeanDaoConfig.initIdentityScope(type);

        diaryDao = new DiaryDao(diaryDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        bodyWeightBeanDao = new BodyWeightBeanDao(bodyWeightBeanDaoConfig, this);

        registerDao(Diary.class, diaryDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(BodyWeightBean.class, bodyWeightBeanDao);
    }
    
    public void clear() {
        diaryDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        bodyWeightBeanDaoConfig.clearIdentityScope();
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public BodyWeightBeanDao getBodyWeightBeanDao() {
        return bodyWeightBeanDao;
    }

}
